# Generated by Django 2.2.12 on 2021-09-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Text',
            field=models.TextField(),
        ),
    ]
