# Generated by Django 2.2.12 on 2021-09-23 07:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210922_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
