# Generated by Django 2.2.12 on 2021-09-24 11:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_galleryabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='public/customer/img')),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
