# Generated by Django 2.2.12 on 2021-09-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_social'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social',
            new_name='Socials',
        ),
    ]
