# Generated by Django 2.2.12 on 2021-09-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_socials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
